//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
// 
#pragma warning disable 1591

namespace KFGCMS.BLL.ZainMessenger {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MessengerSoap", Namespace="http://pmmsoapmessenger.com/")]
    public partial class Messenger : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSms2OperationCompleted;
        
        private System.Threading.SendOrPostCallback HTTP_SendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBinarySmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback HTTP_SendBinarySmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback HTTP_GetSmsStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSmsStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback HTTP_AuthenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendServiceSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback KeepAliveOperationCompleted;
        
        private System.Threading.SendOrPostCallback HTTP_KeepAliveOperationCompleted;
        
        private System.Threading.SendOrPostCallback HTTP_InboxProcessingOperationCompleted;
        
        private System.Threading.SendOrPostCallback InboxProcessingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Messenger() {
            this.Url = global::KFGCMS.BLL.Properties.Settings.Default.KFGCMS_BLL_ZainMessenger_Messenger;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendSmsCompletedEventHandler SendSmsCompleted;
        
        /// <remarks/>
        public event SendSms2CompletedEventHandler SendSms2Completed;
        
        /// <remarks/>
        public event HTTP_SendSmsCompletedEventHandler HTTP_SendSmsCompleted;
        
        /// <remarks/>
        public event SendMMSCompletedEventHandler SendMMSCompleted;
        
        /// <remarks/>
        public event SendBinarySmsCompletedEventHandler SendBinarySmsCompleted;
        
        /// <remarks/>
        public event HTTP_SendBinarySmsCompletedEventHandler HTTP_SendBinarySmsCompleted;
        
        /// <remarks/>
        public event HTTP_GetSmsStatusCompletedEventHandler HTTP_GetSmsStatusCompleted;
        
        /// <remarks/>
        public event GetSmsStatusCompletedEventHandler GetSmsStatusCompleted;
        
        /// <remarks/>
        public event HTTP_AuthenticateCompletedEventHandler HTTP_AuthenticateCompleted;
        
        /// <remarks/>
        public event AuthenticateCompletedEventHandler AuthenticateCompleted;
        
        /// <remarks/>
        public event SendServiceSmsCompletedEventHandler SendServiceSmsCompleted;
        
        /// <remarks/>
        public event KeepAliveCompletedEventHandler KeepAliveCompleted;
        
        /// <remarks/>
        public event HTTP_KeepAliveCompletedEventHandler HTTP_KeepAliveCompleted;
        
        /// <remarks/>
        public event HTTP_InboxProcessingCompletedEventHandler HTTP_InboxProcessingCompleted;
        
        /// <remarks/>
        public event InboxProcessingCompletedEventHandler InboxProcessingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/SendSms", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResult SendSms(SoapUser user, string originator, string smsText, string recipientPhone, MessageType messageType, string defDate, bool blink, bool flash, bool Private) {
            object[] results = this.Invoke("SendSms", new object[] {
                        user,
                        originator,
                        smsText,
                        recipientPhone,
                        messageType,
                        defDate,
                        blink,
                        flash,
                        Private});
            return ((SendResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsAsync(SoapUser user, string originator, string smsText, string recipientPhone, MessageType messageType, string defDate, bool blink, bool flash, bool Private) {
            this.SendSmsAsync(user, originator, smsText, recipientPhone, messageType, defDate, blink, flash, Private, null);
        }
        
        /// <remarks/>
        public void SendSmsAsync(SoapUser user, string originator, string smsText, string recipientPhone, MessageType messageType, string defDate, bool blink, bool flash, bool Private, object userState) {
            if ((this.SendSmsOperationCompleted == null)) {
                this.SendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsOperationCompleted);
            }
            this.InvokeAsync("SendSms", new object[] {
                        user,
                        originator,
                        smsText,
                        recipientPhone,
                        messageType,
                        defDate,
                        blink,
                        flash,
                        Private}, this.SendSmsOperationCompleted, userState);
        }
        
        private void OnSendSmsOperationCompleted(object arg) {
            if ((this.SendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsCompleted(this, new SendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/SendSms2", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResult SendSms2(SoapUser user, string originator, string smsText, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] recipientPhonesFile, MessageType messageType, string defDate, bool flash) {
            object[] results = this.Invoke("SendSms2", new object[] {
                        user,
                        originator,
                        smsText,
                        recipientPhonesFile,
                        messageType,
                        defDate,
                        flash});
            return ((SendResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendSms2Async(SoapUser user, string originator, string smsText, byte[] recipientPhonesFile, MessageType messageType, string defDate, bool flash) {
            this.SendSms2Async(user, originator, smsText, recipientPhonesFile, messageType, defDate, flash, null);
        }
        
        /// <remarks/>
        public void SendSms2Async(SoapUser user, string originator, string smsText, byte[] recipientPhonesFile, MessageType messageType, string defDate, bool flash, object userState) {
            if ((this.SendSms2OperationCompleted == null)) {
                this.SendSms2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSms2OperationCompleted);
            }
            this.InvokeAsync("SendSms2", new object[] {
                        user,
                        originator,
                        smsText,
                        recipientPhonesFile,
                        messageType,
                        defDate,
                        flash}, this.SendSms2OperationCompleted, userState);
        }
        
        private void OnSendSms2OperationCompleted(object arg) {
            if ((this.SendSms2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSms2Completed(this, new SendSms2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/HTTP_SendSms", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResult HTTP_SendSms(int customerID, string userName, string userPassword, string originator, string smsText, string recipientPhone, MessageType messageType, string defDate, bool blink, bool flash, bool Private) {
            object[] results = this.Invoke("HTTP_SendSms", new object[] {
                        customerID,
                        userName,
                        userPassword,
                        originator,
                        smsText,
                        recipientPhone,
                        messageType,
                        defDate,
                        blink,
                        flash,
                        Private});
            return ((SendResult)(results[0]));
        }
        
        /// <remarks/>
        public void HTTP_SendSmsAsync(int customerID, string userName, string userPassword, string originator, string smsText, string recipientPhone, MessageType messageType, string defDate, bool blink, bool flash, bool Private) {
            this.HTTP_SendSmsAsync(customerID, userName, userPassword, originator, smsText, recipientPhone, messageType, defDate, blink, flash, Private, null);
        }
        
        /// <remarks/>
        public void HTTP_SendSmsAsync(int customerID, string userName, string userPassword, string originator, string smsText, string recipientPhone, MessageType messageType, string defDate, bool blink, bool flash, bool Private, object userState) {
            if ((this.HTTP_SendSmsOperationCompleted == null)) {
                this.HTTP_SendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHTTP_SendSmsOperationCompleted);
            }
            this.InvokeAsync("HTTP_SendSms", new object[] {
                        customerID,
                        userName,
                        userPassword,
                        originator,
                        smsText,
                        recipientPhone,
                        messageType,
                        defDate,
                        blink,
                        flash,
                        Private}, this.HTTP_SendSmsOperationCompleted, userState);
        }
        
        private void OnHTTP_SendSmsOperationCompleted(object arg) {
            if ((this.HTTP_SendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HTTP_SendSmsCompleted(this, new HTTP_SendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/SendMMS", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendMMSResult SendMMS([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] mm7Data) {
            object[] results = this.Invoke("SendMMS", new object[] {
                        mm7Data});
            return ((SendMMSResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendMMSAsync(byte[] mm7Data) {
            this.SendMMSAsync(mm7Data, null);
        }
        
        /// <remarks/>
        public void SendMMSAsync(byte[] mm7Data, object userState) {
            if ((this.SendMMSOperationCompleted == null)) {
                this.SendMMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMMSOperationCompleted);
            }
            this.InvokeAsync("SendMMS", new object[] {
                        mm7Data}, this.SendMMSOperationCompleted, userState);
        }
        
        private void OnSendMMSOperationCompleted(object arg) {
            if ((this.SendMMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMMSCompleted(this, new SendMMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/SendBinarySms", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResult SendBinarySms(SoapUser user, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID) {
            object[] results = this.Invoke("SendBinarySms", new object[] {
                        user,
                        originator,
                        binaryBody,
                        recipientPhone,
                        defDate,
                        data_coding,
                        esm_class,
                        PID});
            return ((SendResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendBinarySmsAsync(SoapUser user, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID) {
            this.SendBinarySmsAsync(user, originator, binaryBody, recipientPhone, defDate, data_coding, esm_class, PID, null);
        }
        
        /// <remarks/>
        public void SendBinarySmsAsync(SoapUser user, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID, object userState) {
            if ((this.SendBinarySmsOperationCompleted == null)) {
                this.SendBinarySmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBinarySmsOperationCompleted);
            }
            this.InvokeAsync("SendBinarySms", new object[] {
                        user,
                        originator,
                        binaryBody,
                        recipientPhone,
                        defDate,
                        data_coding,
                        esm_class,
                        PID}, this.SendBinarySmsOperationCompleted, userState);
        }
        
        private void OnSendBinarySmsOperationCompleted(object arg) {
            if ((this.SendBinarySmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBinarySmsCompleted(this, new SendBinarySmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/HTTP_SendBinarySms", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResult HTTP_SendBinarySms(int customerID, string userName, string userPassword, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID) {
            object[] results = this.Invoke("HTTP_SendBinarySms", new object[] {
                        customerID,
                        userName,
                        userPassword,
                        originator,
                        binaryBody,
                        recipientPhone,
                        defDate,
                        data_coding,
                        esm_class,
                        PID});
            return ((SendResult)(results[0]));
        }
        
        /// <remarks/>
        public void HTTP_SendBinarySmsAsync(int customerID, string userName, string userPassword, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID) {
            this.HTTP_SendBinarySmsAsync(customerID, userName, userPassword, originator, binaryBody, recipientPhone, defDate, data_coding, esm_class, PID, null);
        }
        
        /// <remarks/>
        public void HTTP_SendBinarySmsAsync(int customerID, string userName, string userPassword, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID, object userState) {
            if ((this.HTTP_SendBinarySmsOperationCompleted == null)) {
                this.HTTP_SendBinarySmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHTTP_SendBinarySmsOperationCompleted);
            }
            this.InvokeAsync("HTTP_SendBinarySms", new object[] {
                        customerID,
                        userName,
                        userPassword,
                        originator,
                        binaryBody,
                        recipientPhone,
                        defDate,
                        data_coding,
                        esm_class,
                        PID}, this.HTTP_SendBinarySmsOperationCompleted, userState);
        }
        
        private void OnHTTP_SendBinarySmsOperationCompleted(object arg) {
            if ((this.HTTP_SendBinarySmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HTTP_SendBinarySmsCompleted(this, new HTTP_SendBinarySmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/HTTP_GetSmsStatus", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SmsStatus HTTP_GetSmsStatus(int customerID, string userName, string userPassword, string transactionID, bool detailed) {
            object[] results = this.Invoke("HTTP_GetSmsStatus", new object[] {
                        customerID,
                        userName,
                        userPassword,
                        transactionID,
                        detailed});
            return ((SmsStatus)(results[0]));
        }
        
        /// <remarks/>
        public void HTTP_GetSmsStatusAsync(int customerID, string userName, string userPassword, string transactionID, bool detailed) {
            this.HTTP_GetSmsStatusAsync(customerID, userName, userPassword, transactionID, detailed, null);
        }
        
        /// <remarks/>
        public void HTTP_GetSmsStatusAsync(int customerID, string userName, string userPassword, string transactionID, bool detailed, object userState) {
            if ((this.HTTP_GetSmsStatusOperationCompleted == null)) {
                this.HTTP_GetSmsStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHTTP_GetSmsStatusOperationCompleted);
            }
            this.InvokeAsync("HTTP_GetSmsStatus", new object[] {
                        customerID,
                        userName,
                        userPassword,
                        transactionID,
                        detailed}, this.HTTP_GetSmsStatusOperationCompleted, userState);
        }
        
        private void OnHTTP_GetSmsStatusOperationCompleted(object arg) {
            if ((this.HTTP_GetSmsStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HTTP_GetSmsStatusCompleted(this, new HTTP_GetSmsStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/GetSmsStatus", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SmsStatus GetSmsStatus(SoapUser user, string transactionID, bool detailed) {
            object[] results = this.Invoke("GetSmsStatus", new object[] {
                        user,
                        transactionID,
                        detailed});
            return ((SmsStatus)(results[0]));
        }
        
        /// <remarks/>
        public void GetSmsStatusAsync(SoapUser user, string transactionID, bool detailed) {
            this.GetSmsStatusAsync(user, transactionID, detailed, null);
        }
        
        /// <remarks/>
        public void GetSmsStatusAsync(SoapUser user, string transactionID, bool detailed, object userState) {
            if ((this.GetSmsStatusOperationCompleted == null)) {
                this.GetSmsStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSmsStatusOperationCompleted);
            }
            this.InvokeAsync("GetSmsStatus", new object[] {
                        user,
                        transactionID,
                        detailed}, this.GetSmsStatusOperationCompleted, userState);
        }
        
        private void OnGetSmsStatusOperationCompleted(object arg) {
            if ((this.GetSmsStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSmsStatusCompleted(this, new GetSmsStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/HTTP_Authenticate", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AuthResult HTTP_Authenticate(int customerID, string userName, string userPassword) {
            object[] results = this.Invoke("HTTP_Authenticate", new object[] {
                        customerID,
                        userName,
                        userPassword});
            return ((AuthResult)(results[0]));
        }
        
        /// <remarks/>
        public void HTTP_AuthenticateAsync(int customerID, string userName, string userPassword) {
            this.HTTP_AuthenticateAsync(customerID, userName, userPassword, null);
        }
        
        /// <remarks/>
        public void HTTP_AuthenticateAsync(int customerID, string userName, string userPassword, object userState) {
            if ((this.HTTP_AuthenticateOperationCompleted == null)) {
                this.HTTP_AuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHTTP_AuthenticateOperationCompleted);
            }
            this.InvokeAsync("HTTP_Authenticate", new object[] {
                        customerID,
                        userName,
                        userPassword}, this.HTTP_AuthenticateOperationCompleted, userState);
        }
        
        private void OnHTTP_AuthenticateOperationCompleted(object arg) {
            if ((this.HTTP_AuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HTTP_AuthenticateCompleted(this, new HTTP_AuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/Authenticate", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AuthResult Authenticate(SoapUser user) {
            object[] results = this.Invoke("Authenticate", new object[] {
                        user});
            return ((AuthResult)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateAsync(SoapUser user) {
            this.AuthenticateAsync(user, null);
        }
        
        /// <remarks/>
        public void AuthenticateAsync(SoapUser user, object userState) {
            if ((this.AuthenticateOperationCompleted == null)) {
                this.AuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateOperationCompleted);
            }
            this.InvokeAsync("Authenticate", new object[] {
                        user}, this.AuthenticateOperationCompleted, userState);
        }
        
        private void OnAuthenticateOperationCompleted(object arg) {
            if ((this.AuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/SendServiceSms", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResult SendServiceSms(int customerID, string userName, string userPassword, string originator, string serviceName, string serviceUrl, string recipientPhone, MessageType messageType, string defDate, bool blink, bool flash, bool Private) {
            object[] results = this.Invoke("SendServiceSms", new object[] {
                        customerID,
                        userName,
                        userPassword,
                        originator,
                        serviceName,
                        serviceUrl,
                        recipientPhone,
                        messageType,
                        defDate,
                        blink,
                        flash,
                        Private});
            return ((SendResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendServiceSmsAsync(int customerID, string userName, string userPassword, string originator, string serviceName, string serviceUrl, string recipientPhone, MessageType messageType, string defDate, bool blink, bool flash, bool Private) {
            this.SendServiceSmsAsync(customerID, userName, userPassword, originator, serviceName, serviceUrl, recipientPhone, messageType, defDate, blink, flash, Private, null);
        }
        
        /// <remarks/>
        public void SendServiceSmsAsync(int customerID, string userName, string userPassword, string originator, string serviceName, string serviceUrl, string recipientPhone, MessageType messageType, string defDate, bool blink, bool flash, bool Private, object userState) {
            if ((this.SendServiceSmsOperationCompleted == null)) {
                this.SendServiceSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendServiceSmsOperationCompleted);
            }
            this.InvokeAsync("SendServiceSms", new object[] {
                        customerID,
                        userName,
                        userPassword,
                        originator,
                        serviceName,
                        serviceUrl,
                        recipientPhone,
                        messageType,
                        defDate,
                        blink,
                        flash,
                        Private}, this.SendServiceSmsOperationCompleted, userState);
        }
        
        private void OnSendServiceSmsOperationCompleted(object arg) {
            if ((this.SendServiceSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendServiceSmsCompleted(this, new SendServiceSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/KeepAlive", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CommonResult KeepAlive(SoapUser user) {
            object[] results = this.Invoke("KeepAlive", new object[] {
                        user});
            return ((CommonResult)(results[0]));
        }
        
        /// <remarks/>
        public void KeepAliveAsync(SoapUser user) {
            this.KeepAliveAsync(user, null);
        }
        
        /// <remarks/>
        public void KeepAliveAsync(SoapUser user, object userState) {
            if ((this.KeepAliveOperationCompleted == null)) {
                this.KeepAliveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKeepAliveOperationCompleted);
            }
            this.InvokeAsync("KeepAlive", new object[] {
                        user}, this.KeepAliveOperationCompleted, userState);
        }
        
        private void OnKeepAliveOperationCompleted(object arg) {
            if ((this.KeepAliveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KeepAliveCompleted(this, new KeepAliveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/HTTP_KeepAlive", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CommonResult HTTP_KeepAlive(int customerID, string userName, string userPassword) {
            object[] results = this.Invoke("HTTP_KeepAlive", new object[] {
                        customerID,
                        userName,
                        userPassword});
            return ((CommonResult)(results[0]));
        }
        
        /// <remarks/>
        public void HTTP_KeepAliveAsync(int customerID, string userName, string userPassword) {
            this.HTTP_KeepAliveAsync(customerID, userName, userPassword, null);
        }
        
        /// <remarks/>
        public void HTTP_KeepAliveAsync(int customerID, string userName, string userPassword, object userState) {
            if ((this.HTTP_KeepAliveOperationCompleted == null)) {
                this.HTTP_KeepAliveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHTTP_KeepAliveOperationCompleted);
            }
            this.InvokeAsync("HTTP_KeepAlive", new object[] {
                        customerID,
                        userName,
                        userPassword}, this.HTTP_KeepAliveOperationCompleted, userState);
        }
        
        private void OnHTTP_KeepAliveOperationCompleted(object arg) {
            if ((this.HTTP_KeepAliveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HTTP_KeepAliveCompleted(this, new HTTP_KeepAliveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/HTTP_InboxProcessing", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode HTTP_InboxProcessing(int customerID, string userName, string userPassword, string operation, string messageId) {
            object[] results = this.Invoke("HTTP_InboxProcessing", new object[] {
                        customerID,
                        userName,
                        userPassword,
                        operation,
                        messageId});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void HTTP_InboxProcessingAsync(int customerID, string userName, string userPassword, string operation, string messageId) {
            this.HTTP_InboxProcessingAsync(customerID, userName, userPassword, operation, messageId, null);
        }
        
        /// <remarks/>
        public void HTTP_InboxProcessingAsync(int customerID, string userName, string userPassword, string operation, string messageId, object userState) {
            if ((this.HTTP_InboxProcessingOperationCompleted == null)) {
                this.HTTP_InboxProcessingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHTTP_InboxProcessingOperationCompleted);
            }
            this.InvokeAsync("HTTP_InboxProcessing", new object[] {
                        customerID,
                        userName,
                        userPassword,
                        operation,
                        messageId}, this.HTTP_InboxProcessingOperationCompleted, userState);
        }
        
        private void OnHTTP_InboxProcessingOperationCompleted(object arg) {
            if ((this.HTTP_InboxProcessingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HTTP_InboxProcessingCompleted(this, new HTTP_InboxProcessingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pmmsoapmessenger.com/InboxProcessing", RequestNamespace="http://pmmsoapmessenger.com/", ResponseNamespace="http://pmmsoapmessenger.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode InboxProcessing(SoapUser user, string operation, string messageId) {
            object[] results = this.Invoke("InboxProcessing", new object[] {
                        user,
                        operation,
                        messageId});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void InboxProcessingAsync(SoapUser user, string operation, string messageId) {
            this.InboxProcessingAsync(user, operation, messageId, null);
        }
        
        /// <remarks/>
        public void InboxProcessingAsync(SoapUser user, string operation, string messageId, object userState) {
            if ((this.InboxProcessingOperationCompleted == null)) {
                this.InboxProcessingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInboxProcessingOperationCompleted);
            }
            this.InvokeAsync("InboxProcessing", new object[] {
                        user,
                        operation,
                        messageId}, this.InboxProcessingOperationCompleted, userState);
        }
        
        private void OnInboxProcessingOperationCompleted(object arg) {
            if ((this.InboxProcessingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InboxProcessingCompleted(this, new InboxProcessingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public partial class SoapUser {
        
        private int customerIDField;
        
        private string nameField;
        
        private string languageField;
        
        private string passwordField;
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SmsStatus))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendMMSResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public partial class CommonResult {
        
        private string resultField;
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public partial class AuthResult : CommonResult {
        
        private string netPointsField;
        
        private string[] originatorsField;
        
        private int customerIDField;
        
        private string creditSMSField;
        
        private string creditMMSField;
        
        /// <remarks/>
        public string NetPoints {
            get {
                return this.netPointsField;
            }
            set {
                this.netPointsField = value;
            }
        }
        
        /// <remarks/>
        public string[] Originators {
            get {
                return this.originatorsField;
            }
            set {
                this.originatorsField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CreditSMS {
            get {
                return this.creditSMSField;
            }
            set {
                this.creditSMSField = value;
            }
        }
        
        /// <remarks/>
        public string CreditMMS {
            get {
                return this.creditMMSField;
            }
            set {
                this.creditMMSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public partial class SmsStatus : CommonResult {
        
        private System.Xml.XmlNode statisticsField;
        
        private System.Xml.XmlNode detailsField;
        
        private string netPointsField;
        
        /// <remarks/>
        public System.Xml.XmlNode Statistics {
            get {
                return this.statisticsField;
            }
            set {
                this.statisticsField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public string NetPoints {
            get {
                return this.netPointsField;
            }
            set {
                this.netPointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendMMSResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public partial class SendResult : CommonResult {
        
        private string[] rejectedNumbersField;
        
        private string transactionIDField;
        
        private string netPointsField;
        
        /// <remarks/>
        public string[] RejectedNumbers {
            get {
                return this.rejectedNumbersField;
            }
            set {
                this.rejectedNumbersField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string NetPoints {
            get {
                return this.netPointsField;
            }
            set {
                this.netPointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public partial class SendMMSResult : SendResult {
        
        private string mMWLTransactionIDField;
        
        /// <remarks/>
        public string MMWLTransactionID {
            get {
                return this.mMWLTransactionIDField;
            }
            set {
                this.mMWLTransactionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public enum MessageType {
        
        /// <remarks/>
        Latin,
        
        /// <remarks/>
        ArabicWithArabicNumbers,
        
        /// <remarks/>
        ArabicWithLatinNumbers,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendSmsCompletedEventHandler(object sender, SendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendSms2CompletedEventHandler(object sender, SendSms2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSms2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSms2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HTTP_SendSmsCompletedEventHandler(object sender, HTTP_SendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HTTP_SendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HTTP_SendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendMMSCompletedEventHandler(object sender, SendMMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendMMSResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendMMSResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendBinarySmsCompletedEventHandler(object sender, SendBinarySmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBinarySmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBinarySmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HTTP_SendBinarySmsCompletedEventHandler(object sender, HTTP_SendBinarySmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HTTP_SendBinarySmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HTTP_SendBinarySmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HTTP_GetSmsStatusCompletedEventHandler(object sender, HTTP_GetSmsStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HTTP_GetSmsStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HTTP_GetSmsStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SmsStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SmsStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSmsStatusCompletedEventHandler(object sender, GetSmsStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSmsStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSmsStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SmsStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SmsStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HTTP_AuthenticateCompletedEventHandler(object sender, HTTP_AuthenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HTTP_AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HTTP_AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AuthenticateCompletedEventHandler(object sender, AuthenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendServiceSmsCompletedEventHandler(object sender, SendServiceSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendServiceSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendServiceSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void KeepAliveCompletedEventHandler(object sender, KeepAliveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KeepAliveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KeepAliveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CommonResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CommonResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HTTP_KeepAliveCompletedEventHandler(object sender, HTTP_KeepAliveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HTTP_KeepAliveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HTTP_KeepAliveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CommonResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CommonResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HTTP_InboxProcessingCompletedEventHandler(object sender, HTTP_InboxProcessingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HTTP_InboxProcessingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HTTP_InboxProcessingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InboxProcessingCompletedEventHandler(object sender, InboxProcessingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InboxProcessingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InboxProcessingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591